- name: Echo hostname playbook
  hosts: all
  tasks:
    - name: Wait until SSH is available
      ansible.builtin.wait_for_connection:
        timeout: 180
        sleep: 30

    - name: Echo hostname
      command: hostname
      register: hostname_output

    - name: Echo Environment
      command: env
      register: env_output

    - name: Display hostname
      debug:
        msg: "The hostname is {{ hostname_output.stdout }}"

    - name: Display environment
      debug:
        msg: "The environment is {{ env_output.stdout }}"
