- name: Echo hostname playbook
  hosts: all
  tasks:
    - name: Wait for SSH connectivity on each host
      ansible.builtin.wait_for_connection:
        delay: 10      # Wait 10 seconds before the first check
        timeout: 600   # Total timeout of 600 seconds per host
      register: connection_status
      until: connection_status is succeeded
      retries: 10    # Retry 10 times until successful

    - name: Echo hostname
      command: hostname
      register: hostname_output

    - name: Echo Environment
      command: env
      register: env_output

    - name: Display hostname
      debug:
        msg: "The hostname is {{ hostname_output.stdout }}"

    - name: Display environment
      debug:
        msg: "The environment is {{ env_output.stdout }}"
