- name: Echo hostname playbook
  hosts: all
  #become: yes  # This allows Ansible to use sudo

  tasks:
    - name: Echo hostname
      command: hostname
      register: hostname_output

    - name: Echo Environment
      command: env
      register: env_output

    - name: Display hostname
      debug:
        msg: "The hostname is {{ hostname_output.stdout }}"
    - name: Display environment
      debug:
        msg: "The hostname is {{ env_output.stdout }}"
