- name: Resilient Echo hostname playbook
  hosts: all
  gather_facts: false

  tasks:
    - name: Wait until SSH is available
      ansible.builtin.wait_for_connection:
        delay: 45
        timeout: 180
        sleep: 30
      register: connection_wait
      ignore_errors: yes

    - name: Check connection status
      debug:
        msg: "Host is reachable"
      when: connection_wait is succeeded

    - block:
        - name: Echo hostname with retries
          command: hostname
          register: hostname_output
          until: hostname_output.rc == 0
          retries: 3
          delay: 10

        - name: Echo environment with retries
          command: env
          register: env_output
          until: env_output.rc == 0
          retries: 3
          delay: 10

        - name: Display hostname
          debug:
            msg: "The hostname is {{ hostname_output.stdout }}"

        - name: Display environment
          debug:
            msg: "The environment is {{ env_output.stdout }}"
      when: connection_wait is succeeded
      rescue:
        - name: Log unreachable host
          debug:
            msg: "Host is unreachable after waiting. Skipping this host."
